[package]
name = "shared"
version = "0.9.0"
edition = "2024"
description = "Shared functionality for bard"
authors = ["wind_mask","Guilherme Puszkarek"]
license = "MIT"

[dependencies]
anyhow = "1.0"
# For lyrics manipulation
regex = "1.5"
lofty = "0.22.2"
mpris = "2.0.1"
